<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @param array $element
 * @param FormStateInterface $form_state
 * @param $complete_form
 */
function fgt_customize_field_group_form_process_build_alter(array &$element, FormStateInterface $form_state, &$complete_form) {
  foreach ($element['#fieldgroups'] as $group_name => $group) {
    if ($group->format_type !== 'fgt_customize') {
      continue;
    }
    $children = !empty($group->children) ? $group->children : NULL;
    if (!$children) {
      continue;
    }
    foreach ($children as $key => $field_name) {
      if (isset($element[$field_name])) {
        unset($element[$field_name]);
      }
    }
  }
}
